"""Generate full AI Agent interview prep document.

Strategy: build sections as list-of-strings, join and write.
Each section is a dedicated function for readability.
"""
import sys
sys.stdout.reconfigure(encoding='utf-8')

OUT = 'C:/Users/22414/dev/juice094/求职战备/通用八股/ai-agent-八股文.md'

def emit(buf, s=''):
    buf.append(s)

HEAD = []
def sec_header(buf):
    emit(buf, '# AI Agent 方向面试八股文')
    emit(buf)
    emit(buf, '> 候选人：周景潇 | 22岁本科 | Clarity（AI Agent 运行时）+ Devbase（AI 世界模型编译器）')
    emit(buf, '> 核心优势：MCP 协议深度实践、ReAct Agent 循环、RAG 混合搜索、Candle GGUF 本地推理')
    emit(buf, '> 生成日期：2026-06-27')
    emit(buf)
    emit(buf, '---')
    emit(buf)

def sec_toc(buf):
    emit(buf, '## 目录')
    emit(buf)
    emit(buf, '1. [LLM 基础](#1-llm-基础)')
    emit(buf, '2. [Agent 架构](#2-agent-架构)')
    emit(buf, '3. [MCP 协议](#3-mcp-协议)')
    emit(buf, '4. [RAG 检索增强生成](#4-rag-检索增强生成)')
    emit(buf, '5. [本地推理与模型部署](#5-本地推理与模型部署)')
    emit(buf, '6. [AI 应用工程化](#6-ai-应用工程化)')
    emit(buf, '7. [开放性问题](#7-开放性问题)')
    emit(buf)
    emit(buf, '---')
    emit(buf)

def sec_freq_legend(buf):
    emit(buf, '## 考试频率与难度标注说明')
    emit(buf)
    emit(buf, '| 标注 | 含义 | 应对策略 |')
    emit(buf, '|------|------|----------|')
    emit(buf, '| ⭐⭐⭐⭐⭐ | 必考核心，必须滚瓜烂熟 | 能即兴写出关键代码片段，能画出架构图 |')
    emit(buf, '| ⭐⭐⭐⭐ | 高频考点，需要深入理解 | 能讲清楚原理、trade-off、自己的实践经验 |')
    emit(buf, '| ⭐⭐⭐ | 常见考点，需要知道概念和场景 | 能说清楚是什么、什么时候用、为什么用 |')
    emit(buf, '| ⭐⭐ | 加分项，知道更好 | 了解概念，能关联到实际场景 |')
    emit(buf, '| ⭐ | 极少考但展示深度 | 知道即可，不要强答 |')
    emit(buf)
    emit(buf, '---')
    emit(buf)

# ============================================================
# Section 1: LLM 基础
# ============================================================
def sec1_llm_basics(buf):
    emit(buf, '## 1. LLM 基础')
    emit(buf)
    emit(buf, '### 1.1 Transformer 架构核心（⭐⭐⭐⭐⭐）')
    emit(buf)
    emit(buf, '**考点频率**：几乎是每一场面试的必问题。面试官会从"请简述 Transformer 架构"开始，逐步深入 Attention 计算细节。')
    emit(buf)
    emit(buf, '**推荐回答结构**：')
    emit(buf)
    emit(buf, '1. **宏观架构**（30秒）：Encoder-Decoder 框架，但 GPT 系只用 Decoder')
    emit(buf, '2. **Self-Attention 计算**（核心，2分钟）：QKV 三个矩阵的来源、维度、计算过程')
    emit(buf, '3. **Multi-Head Attention**（1分钟）：为什么要多头、每个头关注什么')
    emit(buf, '4. **配套组件**（1分钟）：FFN、LayerNorm、残差连接各自的作用')
    emit(buf)
    emit(buf, '#### 1.1.1 Self-Attention 完整计算流程')
    emit(buf)
    emit(buf, '```')
    emit(buf, '输入序列 X: [seq_len, d_model]')
    emit(buf)
    emit(buf, 'Step 1: 线性投影生成 Q, K, V')
    emit(buf, '  Q = X @ W_Q    # W_Q: [d_model, d_k]')
    emit(buf, '  K = X @ W_K    # W_K: [d_model, d_k]')
    emit(buf, '  V = X @ W_V    # W_V: [d_model, d_v]')
    emit(buf, '  # 通常 d_k = d_v = d_model / num_heads')
    emit(buf)
    emit(buf, 'Step 2: 计算注意力分数')
    emit(buf, '  Scores = Q @ K^T / sqrt(d_k)    # [seq_len, seq_len]')
    emit(buf, '  # 除以 sqrt(d_k) 是缩放因子，防止点积过大导致 softmax 梯度消失')
    emit(buf)
    emit(buf, 'Step 3: Softmax + 加权求和')
    emit(buf, '  Attention_Weights = softmax(Scores)   # 每行求和为1')
    emit(buf, '  Output = Attention_Weights @ V        # [seq_len, d_v]')
    emit(buf, '```')
    emit(buf)
    emit(buf, '**面试追问1：「为什么要除以 sqrt(d_k)？」**')
    emit(buf)
    emit(buf, '- [VERIFIED] 当 d_k 较大时，点积 Q·K 的方差会增大（方差 = d_k）')
    emit(buf, '- 未经缩放的点积值进入 softmax 后，分布会极端化（接近 one-hot），梯度趋近于零')
    emit(buf, '- 除以 sqrt(d_k) 将方差归一化到 1，保持梯度流动')
    emit(buf)
    emit(buf, '**面试追问2：「Multi-Head Attention 为什么要多头？」**')
    emit(buf)
    emit(buf, '- 单头只能学习一种注意力模式（如语法关系），多头可以同时学习多种（语法、语义、位置、指代）')
    emit(buf, '- 类比：CNN 的多个卷积核分别检测边缘、纹理、形状')
    emit(buf, '- 每个头的 d_k 较小，总计算量与单头大维度相当')
    emit(buf)
    emit(buf, '**面试追问3：「LayerNorm 和 BatchNorm 的区别？为什么 Transformer 用 LayerNorm？」**')
    emit(buf)
    emit(buf, '| 对比维度 | BatchNorm | LayerNorm |')
    emit(buf, '|----------|-----------|-----------|')
    emit(buf, '| 归一化维度 | 对 batch 维度归一化（每个特征跨样本） | 对 feature 维度归一化（每个样本跨特征） |')
    emit(buf, '| 依赖 batch size | 强依赖，小 batch 时不稳定 | 无关，每个样本独立归一化 |')
    emit(buf, '| 训练/推理差异 | 训练用 batch 统计量，推理用全局统计量 | 训练和推理行为一致 |')
    emit(buf, '| 序列建模适用性 | 差（序列长度不固定，padding 破坏统计） | 好（每个 token 独立归一化） |')
    emit(buf)
    emit(buf, '- Transformer 用 LayerNorm 的核心原因：序列长度可变，batch 内样本长度不一致导致 BN 统计量不可靠')
    emit(buf, '- 现代变体 Pre-LN（先 LayerNorm 再 Attention）比 Post-LN 训练更稳定')
    emit(buf)
    emit(buf, '**面试追问4：「残差连接的作用？没有它会怎样？」**')
    emit(buf)
    emit(buf, '- 数学本质：Output = LayerNorm(x + Sublayer(x))，Sublayer 学习的是残差而非完整映射')
    emit(buf, '- 作用1：梯度高速公路 —— 反向传播时梯度可以直接流过残差分支，缓解深层网络的梯度消失')
    emit(buf, '- 作用2：恒等映射兜底 —— 初始时 Sublayer 输出接近 0，网络行为接近恒等映射，训练更稳定')
    emit(buf, '- [VERIFIED] 去掉残差连接：深层 Transformer（>12层）几乎无法训练，loss 不下降')
    emit(buf)
    emit(buf, '#### 1.1.2 FFN（Feed-Forward Network）的结构与作用')
    emit(buf)
    emit(buf, '```')
    emit(buf, 'FFN(x) = GELU(x @ W1 + b1) @ W2 + b2')
    emit(buf, '# W1: [d_model, d_ff]  通常 d_ff = 4 * d_model')
    emit(buf, '# W2: [d_ff, d_model]')
    emit(buf, '```')
    emit(buf)
    emit(buf, '- Attention 做的是 token 之间的信息混合（"横向"），FFN 做的是每个 token 内部的特征变换（"纵向"）')
    emit(buf, '- 类比：Attention = 开会交流信息，FFN = 每个人独立思考消化')
    emit(buf, '- d_ff 通常设为 d_model 的 4 倍，这是实践中发现的经验最优值')
    emit(buf, '- FFN 存储了大量的知识记忆（有研究表明 MLP 层比 Attention 层存储更多事实知识）')
    emit(buf)
    emit(buf, '#### 1.1.3 面试答题模板')
    emit(buf)
    emit(buf, '```')
    emit(buf, '面试官："请简述 Transformer 架构。"')
    emit(buf)
    emit(buf, '候选人："Transformer 是 2017 年 Google 提出的基于自注意力机制的序列建模架构，')
    emit(buf, '  核心创新是用 Self-Attention 替代 RNN 的循环结构，实现了完全的并行计算。')
    emit(buf)
    emit(buf, '  GPT 系列只用 Decoder 部分。每个 Decoder 层包含三个核心组件：')
    emit(buf, '  1) Masked Multi-Head Self-Attention：计算每个 token 与之前所有 token 的关联权重')
    emit(buf, '  2) FFN：对每个 token 做非线性特征变换，d_ff 通常是 d_model 的 4 倍')
    emit(buf, '  3) 残差连接 + LayerNorm：保证深层网络训练稳定')
    emit(buf)
    emit(buf, '  Attention 的计算核心是：Q、K、V 三个矩阵由输入 X 分别乘以 W_Q/W_K/W_V 得到，')
    emit(buf, '  Score = softmax(QK^T / sqrt(d_k)) 得到注意力权重，再乘以 V 得到输出。')
    emit(buf, '  除以 sqrt(d_k) 是为了防止点积方差过大导致 softmax 梯度消失。')
    emit(buf)
    emit(buf, '  多头机制允许模型同时关注不同子空间的信息，类似于 CNN 的多卷积核。"')
    emit(buf, '```')
    emit(buf)
    emit(buf, '---')
    emit(buf)

    # 1.2 Tokenization
    emit(buf, '### 1.2 Tokenization（⭐⭐⭐⭐）')
    emit(buf)
    emit(buf, '**考点频率**：中高频。面试官会问"你了解哪些分词方法？BPE 的原理是什么？为什么选择某种分词器？"')
    emit(buf)
    emit(buf, '#### 三种主流分词方法对比')
    emit(buf)
    emit(buf, '| 分词方法 | 代表模型/工具 | 核心原理 | 优点 | 缺点 |')
    emit(buf, '|----------|-------------|---------|------|------|')
    emit(buf, '| BPE (Byte-Pair Encoding) | GPT-2/3/4 (tiktoken), RoBERTa | 从字符级开始，迭代合并最高频的 token 对，直到达到目标词表大小 | 平衡粒度，OOV 问题解决得好 | 对罕见字符序列效率低 |')
    emit(buf, '| SentencePiece | LLaMA, Mistral, Gemma | 将文本视为字节流，在 Unicode 字符或字节级别进行 BPE 或 Unigram 分割 | 语言无关，不需要预分词 | 中文等非空格分隔语言的压缩率略低 |')
    emit(buf, '| tiktoken | GPT-3.5/4 (cl100k_base) | OpenAI 自研的 BPE 实现，用 Rust 编写。词表约 100K tokens | 速度极快，训练时就考虑了多语言 | 闭源，不可自定义 |')
    emit(buf)
    emit(buf, '#### BPE 核心原理深入')
    emit(buf)
    emit(buf, 'BPE 的训练过程（不是推理！推理时直接查表）：')
    emit(buf)
    emit(buf, '```')
    emit(buf, '1. 初始化：词表 = 所有 Unicode 字符（约 256 个字节 + 常见字符）')
    emit(buf, '2. 统计：在训练语料上统计所有相邻 token 对的共现频率')
    emit(buf, '3. 合并：选择频率最高的 token 对 (A, B)，将 "AB" 作为新 token 加入词表')
    emit(buf, '4. 重复步骤 2-3，直到词表达到目标大小（如 50K, 100K）')
    emit(buf, '```')
    emit(buf)
    emit(buf, '关键影响：')
    emit(buf, '- **Token 效率**：中文约 1.5-2 字符/token，英文约 4 字符/token（0.75 词/token）。相同语义的中文消耗更多 token')
    emit(buf, '- **数字处理**：GPT 系的 tokenizer 不会将 "12345" 当作一个 token，而是拆分成多位数字组合，导致算术能力弱')
    emit(buf, '- **代码理解**：Python 的 4 空格缩进每个空格是独立的 token（浪费 context window），而 Tab 可能是一个 token')
    emit(buf)
    emit(buf, '**面试追问：「为什么 LLaMA 用 SentencePiece 而 GPT 用 tiktoken？」**')
    emit(buf)
    emit(buf, '- LLaMA 的 SentencePiece 在字节级训练，理论上可以表示任何 Unicode 字符（甚至 emoji），真正做到零 OOV')
    emit(buf, '- GPT 的 tiktoken 是 BPE 变体，词表更大（100K vs 32K），在英文和多语言上压缩率更好')
    emit(buf, '- 本质是设计哲学：开源社区优先语言无关性，闭源商业优先效率')
    emit(buf)
    emit(buf, '#### 候选人实战提示')
    emit(buf)
    emit(buf, '- Clarity 中对接多个模型 provider 时，需要准确计算不同 tokenizer 的 token 数做预算控制')
    emit(buf, '- 实际开发中，使用 `tiktoken` 库精确计数，避免用 `len(text) / 4` 估算（中文偏差很大）')
    emit(buf)
    emit(buf, '---')
    emit(buf)

    # 1.3 Context Window
    emit(buf, '### 1.3 Context Window（⭐⭐⭐⭐⭐）')
    emit(buf)
    emit(buf, '**考点频率**：非常高。从"Attention 复杂度怎么算"到"长上下文怎么处理"，必有一问。')
    emit(buf)
    emit(buf, '#### Attention 的 O(n²) 复杂度')
    emit(buf)
    emit(buf, '```')
    emit(buf, 'Self-Attention 的复杂度分析：')
    emit(buf, '  - QK^T 矩阵乘法：[n, d] @ [d, n] = O(n² * d)')
    emit(buf, '  - Softmax：[n, n] = O(n²)')
    emit(buf, '  - Attention @ V：[n, n] @ [n, d] = O(n² * d)')
    emit(buf, '  - 总时间复杂度：O(n² * d)，其中 n 是序列长度，d 是 hidden dimension')
    emit(buf, '  - 空间复杂度：O(n²) 需要存储注意力矩阵')
    emit(buf)
    emit(buf, '  具体数字：n=128K tokens, d=8192, 需要约 128K^2 * 4 bytes = 65 GB 显存（仅注意力矩阵）')
    emit(buf, '```')
    emit(buf)
    emit(buf, '#### 长上下文的挑战与解决方案')
    emit(buf)
    emit(buf, '| 挑战 | 描述 | 解决方案 |')
    emit(buf, '|------|------|----------|')
    emit(buf, '| 计算复杂度 | O(n²) 随序列长度平方增长 | FlashAttention（IO-aware 分块计算），Ring Attention（分布式） |')
    emit(buf, '| 显存瓶颈 | 注意力矩阵 O(n²) 空间 | KV Cache 量化（INT8/INT4），PagedAttention（vLLM） |')
    emit(buf, '| 位置编码失效 | RoPE 在远超训练长度时外推性能下降 | NTK-aware 缩放，YaRN，Position Interpolation |')
    emit(buf, '| 注意力分散 | 序列过长时注意力被稀释，"Lost in the Middle" 现象 | 检索增强（RAG），分层注意力，关键信息前移 |')
    emit(buf, '| 推理延迟 | 长 prompt 导致首 token 延迟巨大 | Prefix Caching，投机解码（Speculative Decoding） |')
    emit(buf)
    emit(buf, '#### Lost in the Middle 现象')
    emit(buf)
    emit(buf, '- [VERIFIED] 研究发现：模型对长上下文开头和结尾的信息理解最好，中间部分的理解显著下降')
    emit(buf, '- 实践建议：重要指令放开头，关键上下文放结尾，中间放次要信息')
    emit(buf, '- 这与人类阅读长文档的行为类似（首因效应 + 近因效应）')
    emit(buf)
    emit(buf, '#### FlashAttention 原理简述')
    emit(buf)
    emit(buf, '- 核心思想：利用 GPU 显存层级（HBM vs SRAM），通过分块（tiling）计算避免将完整注意力矩阵写入 HBM')
    emit(buf, '- 在线 Softmax：分块计算 softmax 时保持数值稳定性，不需要全局最大值')
    emit(buf, '- 效果：将显存复杂度从 O(n²) 降至 O(n)，速度提升 2-4 倍，且数学上等价于标准 Attention')
    emit(buf, '- [VERIFIED] FlashAttention-3 已集成到 PyTorch 2.0+ 的 `torch.nn.functional.scaled_dot_product_attention`')
    emit(buf)
    emit(buf, '---')
    emit(buf)

    # 1.4 采样策略
    emit(buf, '### 1.4 采样策略（⭐⭐⭐⭐）')
    emit(buf)
    emit(buf, '| 策略 | 原理 | 参数 | 适用场景 |')
    emit(buf, '|------|------|------|----------|')
    emit(buf, '| Temperature | 在 softmax 前将 logits 除以 T。T>1 更随机，T<1 更确定 | T 通常 0.1~2.0 | 控制创意/保守程度 |')
    emit(buf, '| Top-k | 只从概率最高的 k 个 token 中采样 | k 通常 10~50 | 避免低概率垃圾 token |')
    emit(buf, '| Top-p (Nucleus) | 从累积概率达到 p 的最小 token 集合中采样 | p 通常 0.9~0.95 | 动态自适应词汇选择 |')
    emit(buf, '| Beam Search | 保留 top-b 个候选序列，每步扩展 | beam 通常 3~5 | 翻译、代码生成等确定性任务 |')
    emit(buf)
    emit(buf, '**面试追问：「Top-k 和 Top-p 的区别？为什么现在更推荐 Top-p？」**')
    emit(buf)
    emit(buf, '- Top-k 的问题：固定的 k 值无法适应不同上下文的词汇分布。当分布平坦时（很多词都可能），k 可能太小；当分布尖锐时（只有一个词合理），k 包含太多噪声')
    emit(buf, '- Top-p 的优势：动态调整候选集合大小。分布尖锐时集合小（接近 greedy），分布平坦时集合大（保留多样性）')
    emit(buf, '- 实践中 Top-p=0.9 + Temperature=0.7 是通用的"有创意但不离谱"配置')
    emit(buf)
    emit(buf, '**面试追问：「Agent 场景下采样参数如何设置？」**')
    emit(buf)
    emit(buf, '- Tool calling / 推理阶段：Temperature=0（确定性），确保函数调用的 JSON 格式正确、工具名不幻觉')
    emit(buf, '- 自由对话阶段：Temperature=0.7~0.9，保持对话自然度')
    emit(buf, '- 高级做法：不同步骤使用不同的采样参数，推理步骤用 greedy，输出步骤用 sampling')
    emit(buf, '  - Claude API 的 `thinking` 模式实际上内置了这种分层策略')
    emit(buf)
    emit(buf, '---')
    emit(buf)

    # 1.5 Prompt Engineering
    emit(buf, '### 1.5 Prompt Engineering（⭐⭐⭐⭐⭐）')
    emit(buf)
    emit(buf, '**考点频率**：必考。而且不是"你了解哪些 prompt 技巧"，而是"针对这个具体场景你怎么设计 prompt"。')
    emit(buf)
    emit(buf, '#### 五大核心范式对比')
    emit(buf)
    emit(buf, '| 范式 | 原理 | 何时用 | 何时不用 |')
    emit(buf, '|------|------|--------|----------|')
    emit(buf, '| Few-shot | 在 prompt 中提供 N 个示例，让模型模仿格式/风格 | 输出格式固定、任务边界清晰（分类、格式化） | 示例可能误导模型或过拟合到示例模式 |')
    emit(buf, '| Chain-of-Thought (CoT) | 要求模型"一步一步思考"，输出推理过程 | 数学、逻辑、多步推理任务 | 简单任务会引入不必要开销，增加延迟和 token 消耗 |')
    emit(buf, '| ReAct | 交替进行 Reasoning（思考）和 Action（行动），Action 返回 Observation 后继续 Reasoning | 需要外部工具/信息检索的 Agent 场景 | 纯文本任务（没有工具/环境交互） |')
    emit(buf, '| Tree-of-Thoughts (ToT) | 在每个推理步骤探索多个分支，评估后选择最优路径继续 | 需要探索和回溯的规划任务（游戏、数学证明） | 评估成本高（每步 O(branches) 倍），简单任务杀鸡用牛刀 |')
    emit(buf, '| Self-Consistency | 多次采样 + 多数投票，利用采样多样性提高准确率 | 有明确正确答案的推理任务（数学、代码） | 成本翻倍，开放性问题无意义 |')
    emit(buf)
    emit(buf, '#### Few-shot 的设计原则')
    emit(buf)
    emit(buf, '1. **示例质量 > 数量**：3 个高质量示例通常优于 10 个一般示例')
    emit(buf, '2. **示例多样性**：覆盖边界情况和不同输入风格')
    emit(buf, '3. **格式一致性**：示例的输出格式必须与期望完全一致，不一致会严重降低性能')
    emit(buf, '4. **顺序效应**：最后一个示例对输出影响最大（近因效应），把最典型的放最后')
    emit(buf)
    emit(buf, '#### Chain-of-Thought 深入')
    emit(buf)
    emit(buf, '- 零样本 CoT：加一句 `Let\'s think step by step.` 即可触发，约提升 10-30% 推理准确率')
    emit(buf, '- 为什么 CoT 有效？将隐式推理外部化，模型可以看到自己的推理历史，相当于隐式地为最终答案增加了条件概率的证据链')
    emit(buf, '- 风险：模型可能在推理中自我欺骗，一条错误的推理链会导致完全错误的结论')
    emit(buf, '- 缓解：Self-Consistency + CoT，多次推理取共识结论')
    emit(buf)
    emit(buf, '#### System Prompt vs User Prompt')
    emit(buf)
    emit(buf, '| 维度 | System Prompt | User Prompt |')
    emit(buf, '|------|---------------|-------------|')
    emit(buf, '| 角色 | 设定 AI 的身份、能力边界、行为规范 | 具体的任务指令和输入数据 |')
    emit(buf, '| 优先级 | 高于 User（模型被训练为遵循 System 约束） | 在 System 框架内生效 |')
    emit(buf, '| 持久性 | 会话级持久（一次设定，整个对话有效） | 每条消息独立 |')
    emit(buf, '| 典型内容 | "你是一个专业的代码审查者..." | "请审查以下代码中的安全漏洞..." |')
    emit(buf, '| 安全敏感性 | 最高（Prompt Injection 优先攻击 System Prompt） | 中等 |')
    emit(buf)
    emit(buf, '- **最佳实践**：System = 角色+约束+风格+工具声明；User = 具体任务+上下文+格式要求')
    emit(buf, '- **常见错误**：把过多具体任务放在 System 中（System 是框架不是流水账），或者把角色约束放在每个 User 消息里重复（浪费 context）')
    emit(buf)
    emit(buf, '---')
    emit(buf)
    emit(buf)

print('Section 1 function defined.')
